### ISSUE TITLE
Regarding assignment 2

### ISSUE THREAD

**Issue by innovation-stack** [anamica08/Angular-Assignment#1]
The way you have rendered rows is not the angular way. Please check my session on how to render rows.

```
<table>
  <tbody>
    <tr *ngFor="let todo of todos" [ngClass]="{active: todo === selectedTodo}" (click)="selectTodo(todo)>
   </tbody>
</table>
```
```
selectTodo(todo) {
  this.selectedTodo = todo;
}
```

**Comment by anamica08** [comment]
I have fixed this issue.
Tried it earlier also , but I didn't import common module in child module.
